- ios/Podfile.lock
- src/components/Input/index.tsx
- src/components/Input/styled/error.ts
- src/components/Input/styled/input.ts
- src/components/Input/styled/label.ts
- src/styles/colors.ts
- src/styles/shadows.ts
> styles: input

- ios/Podfile.lock
- ios/ReactNativeRainbow.xcodeproj/project.pbxproj
- src/components/Icons/arrowDown.js
- src/components/InputPhone/countyPickerModal/countries.tsx
- src/components/InputPhone/countyPickerModal/header.tsx
- src/components/InputPhone/countyPickerModal/list.tsx
- src/components/InputPhone/countyPickerModal/listItem.tsx
- src/components/InputPhone/countyPickerModal/styled.ts
- src/components/InputPhone/index.tsx
- src/components/InputPhone/styled.ts
> fix: fix InputPhone

- src/components/Button/buttonContent.tsx
- src/components/Button/index.tsx
> feat: fix button content

- src/components/Button/index.tsx
- src/components/Button/styled/index.ts
- src/components/Input/index.tsx
- src/components/Input/styled/index.ts
- src/components/Input/styled/input.ts
- src/components/types.d.ts
- storybook/stories/input.stories.js
fix: #28 
-
enhance the input component by adding icon prop
> feat: implement prop `icon` on the Input component

- src/components/Icons/magnifying.tsx
- src/components/InputPhone/countyPickerModal/header.tsx
- src/components/InputPhone/countyPickerModal/styled/index.ts
> feat: add icon to InputPhone modal

- src/components/index.ts
> fix: add progressCircular to index

- src/components/Button/styled/index.ts
- src/components/ButtonIcon/index.tsx
- src/components/ButtonIcon/styled/index.ts
- src/components/types.d.ts
- storybook/stories/buttonIcon.stories.js
> styles: fix button and buttonicon

- src/components/index.ts
> fix: import Modal

- src/components/InputPhone/index.tsx
> fix: inputPhone when type first the phone number and then select the country

- src/components/Input/index.tsx
- src/components/InputPhone/index.tsx
- src/hocs/withReduxForm.tsx
> feat: add withReduxForm hoc

- src/components/InputCode/__tests__/inputCode.spec.tsx
- src/components/InputCode/helpers/__tests__/inputCode.spec.tsx
- src/components/InputCode/helpers/getCodeFromClipboard.ts
- src/components/InputCode/index.tsx
-
https://recordit.co/yAqa0L9wWb
> feat: ability to take clipboard values

- src/components/ProgressBar/index.tsx
- src/components/ProgressBar/styled/index.ts
- src/components/ProgressCircular/ProgressCircularSVG.tsx
- src/components/index.ts
- storybook/stories/progressBar.stories.js
> feat: implement progressBar component

- src/components/Modal/index.tsx
- src/components/Modal/styled/index.ts
> styles: modal container

- src/components/LikeButton/index.tsx
- src/components/LikeButton/styled/index.ts
- storybook/stories/likeButton.stories.js
- added like button size variant
> feat: added like button size variant

- src/components/InputPhone/helpers/getCountryFromValue.ts
> fix: input phone

- src/components/LikeButton/index.tsx
- src/components/LikeButton/styled/index.ts
- src/styles/shadows.ts
- storybook/stories/likeButton.stories.js
> fix: like button styles

- src/components/LikeButton/styled/index.ts
> styles: fix UI

- ios/Podfile.lock
- ios/ReactNativeRainbow.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- src/components/Button/styled/button.ts
- src/components/ButtonIcon/styled/index.ts
> fix: disable styles

- src/components/SwipeButton/icon.tsx
- src/components/SwipeButton/index.tsx
- src/components/SwipeButton/thumb.tsx
- storybook/stories/swipeButton.stories.js
implement swipe button basic functionality
> feat: swipe-button first commit

- metro.config.js
- package.json
- src/components/FlatList/footer.tsx
- src/components/FlatList/index.tsx
- src/components/FlatList/loadingItem.tsx
- src/components/FlatList/styled.ts
- src/components/FlatList/types.ts
- src/components/index.ts
- storybook/stories/flatList.stories.js
- yarn.lock
> feat: implement FlatList component

- package.json
- src/components/Button/index.tsx
- src/components/FlatList/index.tsx
- src/components/FlatList/styled.ts
- src/components/FlatList/types.ts
- src/components/Icons/chevronBack.tsx
- src/components/ScreenFlatList/header/index.tsx
- src/components/ScreenFlatList/header/styled.ts
- src/components/ScreenFlatList/index.tsx
- src/components/ScreenFlatList/types.ts
- src/components/index.ts
- storybook/stories/flatList.stories.js
- storybook/stories/screenFlatList.stories.js
- yarn.lock
- Implemented ScreenFlatList component
> feat: implement ScreenFlatList component

- src/components/Avatar/index.tsx
- src/components/Avatar/types.ts
- Add `onError` callback to Avatar component.
- Add imperative `refresh` function to Avatar component.
> feat: add `onError` prop to Avatar component

- src/components/SwipeButton/index.tsx
- src/components/SwipeButton/styled.ts
fix: #
- fix: large text in swipe button
> fix: large text in swipe button

- src/components/Icons/minus.tsx
- src/components/Icons/plus.tsx
- src/components/InputCounter/helpers/getNormalizedValue.ts
- src/components/InputCounter/helpers/getValue.ts
- src/components/InputCounter/helpers/isButtonDisabled.ts
- src/components/InputCounter/helpers/isMax.ts
- src/components/InputCounter/helpers/isMin.ts
- src/components/InputCounter/index.tsx
- src/components/InputCounter/styled/index.ts
- src/components/InputCounter/styled/input.ts
- src/components/index.ts
- storybook/stories/inputCounter.stories.js
feat: implement input counter component
-
> feat: implement input counter component

- src/components/Modal/styled/index.ts
fix: add theme support to modal
fix: add theme support to input phone
-
> fix: add theme support to modal

- src/components/SegmentedControl/index.tsx
- src/components/SegmentedControl/styled/index.ts
fix: dark theme and logic segmented control
-
> fix: dark theme and logic segmented control

- src/components/styled.d.ts
- src/components/types.d.ts
- src/styles/helpers/normalizeTheme.ts
feat: implement custom theme
-
> feat: implement custom theme

- src/components/Select/index.tsx
feat: add dark mode to select on ios
-
> feat: add dark mode to select on ios
